#!/bin/python3

import os
import sys

# Complete the countingValleys function below.
def countingValleys(n, s):
    level = 0
    valley = 0

    for sp in s:
        if sp == "U" :
            level = level + 1
        else:
            level = level - 1
        
        if sp == "U" and level == 0:
            valley = valley + 1
    
    return valley

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    s = input()

    result = countingValleys(n, s)

    fptr.write(str(result) + '\n')

    fptr.close()
