#!/bin/python3

import os
import sys



if __name__ == '__main__':
    n = int(input().strip())
    for i in range(1, 10 + 1):
        answer = n * i
        print("{} x {} = {} ".format(n, i, answer))
