#!/bin/python3

import os
import sys

# Complete the repeatedString function below.
def repeatedString(s, n):
    string  = s.count("a")
    nstring = s[0 : n % len(s)].count("a")
    return string * (n // len(s)) + nstring

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    n = int(input())

    result = repeatedString(s, n)

    fptr.write(str(result) + '\n')

    fptr.close()
